export {
	type CommitMatchResult,
	type FileChange,
	type GitOperation,
	type GitVersion,
	type MergeDetectionResult,
	analyzeRetargetReplay,
	assertMinimumGitVersion,
	branchExistsLocally,
	checkBranchMatch,
	detectBranchMerged,
	detectOperation,
	detectRebasedCommits,
	findMergeCommitForBranch,
	findTicketReferencedCommit,
	getCommitsBetween,
	getCommitsBetweenFull,
	getDefaultBranch,
	getDiffShortstat,
	getHeadCommitDate,
	getMergeBase,
	getShortHead,
	git,
	isLinkedWorktree,
	isRepoDirty,
	isShallowRepo,
	parseGitNumstat,
	parseGitStatus,
	parseGitStatusFiles,
	parseGitVersion,
	parseDiffShortstat,
	predictMergeConflict,
	predictRebaseConflictCommits,
	predictStashPopConflict,
	remoteBranchExists,
	validateBranchName,
	validateWorkspaceName,
	verifySquashRange,
	matchDivergedCommits,
} from "./git";
export { GitCache } from "./git-cache";
export { type ParsedRemoteUrl, type RemoteProvider, buildPrUrl, parseRemoteUrl } from "./remote-url";
export { type RepoRemotes, getRemoteNames, getRemoteUrl, resolveRemotes, resolveRemotesMap } from "./remotes";
