export { detectArbRoot, detectWorkspace } from "./arb-root";
export { type WorkspaceBranchResult, workspaceBranch } from "./branch";
export {
	detectSharedWorktreeEntries,
	findOrphanedBranches,
	findStaleWorktrees,
	pruneWorktrees,
	readGitdirFromWorktree,
	repairAllWorktreeRefs,
	repairWorktreeRefs,
} from "./clean";
export { requireBranch, requireWorkspace } from "./context";
export {
	collectRepo,
	findRepoUsage,
	listNonWorkspaces,
	listRepos,
	listWorkspaces,
	selectInteractive,
	selectReposInteractive,
	validateRepoNames,
	workspaceRepoDirs,
	resolveRepoSelection,
} from "./repos";
export {
	ARBTEMPLATE_EXT,
	type ConflictInfo,
	type FailedCopy,
	type ForceOverlayResult,
	type OverlayResult,
	type RemoteInfo,
	type RepoInfo,
	type TemplateDiff,
	type TemplateContext,
	type TemplateEntry,
	type TemplateScope,
	type UnknownVariable,
	applyRepoTemplates,
	applyWorkspaceTemplates,
	checkAllTemplateVariables,
	checkUnknownVariables,
	checkWorkspaceTemplateRepoWarnings,
	detectScopeFromPath,
	diffTemplates,
	displayOverlaySummary,
	displayRepoDirectoryWarnings,
	displayTemplateConflicts,
	displayTemplateDiffs,
	displayUnknownVariables,
	forceApplyRepoTemplates,
	forceApplyWorkspaceTemplates,
	forceOverlayDirectory,
	listTemplates,
	overlayDirectory,
	renderTemplate,
	templateFilePath,
	workspaceFilePath,
	workspaceRepoList,
} from "./templates";
export { type AddWorktreesResult, addWorktrees, isWorktreeRefValid, pruneWorktreeEntriesForDir } from "./worktrees";
