import { bold, dim } from "../terminal";
import type { HelpTopic } from "./types";

export const stackedTopic: HelpTopic = {
  name: "stacked",
  summary: "Stacked workspaces (branching off features)",
  render() {
    const out = (text: string) => process.stdout.write(`${text}\n`);

    out(bold("STACKED WORKSPACES"));
    out("");
    out("  A stacked workspace branches off another feature branch instead of the");
    out("  default branch (e.g. main). This lets you build on work that hasn't");
    out("  been merged yet, creating a chain of dependent feature branches.");
    out("");
    out(bold("CREATING"));
    out("");
    out(`  ${dim("arb create <name> --base <branch>")}`);
    out("");
    out("  The --base flag sets the branch that arb will rebase onto and track.");
    out("  This is stored in .arbws/config.json and used by status, rebase, and merge.");
    out("  Without --base, arb uses the default branch (e.g. main).");
    out("");
    out(bold("STATUS FLAGS"));
    out("");
    out("  Stacked workspaces can have additional status flags:");
    out("");
    out(`    ${bold("behind-base")}    The base branch has new commits not yet integrated`);
    out(`    ${bold("base-merged")}    The configured base branch was merged into the`);
    out("                   default branch (stack collapsed)");
    out(`    ${bold("base-missing")}   The configured base branch was not found;`);
    out("                   fell back to the default branch");
    out("");
    out(bold("MANAGING THE BASE"));
    out("");
    out(`  ${dim("arb branch base")}`);
    out("    Show the current base branch.");
    out("");
    out(`  ${dim("arb branch base <branch>")}`);
    out("    Change the base branch (config only — does not rebase or reset).");
    out("    Blocks if the current base was merged; use --force to override.");
    out("");
    out(`  ${dim("arb branch base --unset")}`);
    out("    Remove the base (track repo default).");
    out("");
    out(bold("RETARGETING"));
    out("");
    out("  Use 'arb retarget' to change the base branch and rebase in one step:");
    out("");
    out(`  ${dim("arb retarget <branch>")}`);
    out("    Retargets onto <branch> and updates .arbws/config.json.");
    out("    Works whether the old base was merged or not.");
    out("");
    out(`  ${dim("arb retarget")}`);
    out("    Without a branch argument, retargets onto the default branch");
    out("    (e.g. main) and removes the configured base.");
    out("");
    out("  To change the base config without rebasing, use 'arb branch base'.");
    out("");
    out(bold("EXAMPLES"));
    out("");
    out(`  ${dim("arb create auth-ui --base feat/auth-api")}`);
    out("    Create a workspace stacked on the auth-api feature branch.");
    out("");
    out(`  ${dim("arb retarget feat/auth-api")}`);
    out("    Retarget a workspace onto feat/auth-api (e.g. to start stacking).");
    out("");
    out(`  ${dim("arb status")}`);
    out("    Shows behind-base if feat/auth-api has new commits,");
    out("    or base-merged if it was merged into main.");
    out("");
    out(`  ${dim("arb retarget")}`);
    out("    After feat/auth-api is merged, retarget onto main.");
    out("");
    out(`  ${dim("arb retarget feat/auth-api")}`);
    out("    In a deeper stack (C on B on A), retarget C onto A.");
    out("");
    out(bold("RETROACTIVE STACKING WITH EXTRACT"));
    out("");
    out("  Use 'arb extract' to split an existing branch into a stack after the fact:");
    out("");
    out(`  ${dim("arb extract prereq --ending-with <commit>")}`);
    out("    Extract the prefix (base through commit) into a new lower workspace.");
    out("    The original workspace stacks on top.");
    out("");
    out(`  ${dim("arb extract cont --starting-with <commit>")}`);
    out("    Extract the suffix (commit through tip) into a new upper workspace.");
    out("    The original workspace keeps the prefix.");
    out("");
    out("  In base-merged workspaces, split points must be at or after the merge point.");
    out("");
    out("  See 'arb extract --help' for split point syntax and multi-repo options.");
  },
};
